safe: false
source: .
destination: _site
lsi: false
markdown: rdiscount
highlighter: pygments
permalink: pretty
baseurl: "http://eadpucv.github.io/pyxis"
project:
name: Pyxis
exclude: [bower_components]
