safe: false
source: .
destination: _gh-pages
lsi: false
markdown: rdiscount
highlighter: pygments
permalink: pretty
baseurl: "http://eadpucv.github.io/pyxis"
project:
name: Pyxis
exclude: [bower_components, less]
version: 3.0.0

